CREATE SCHEMA IF NOT EXISTS catalogue;
CREATE TABLE IF NOT EXISTS catalogue.item_info(
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY ,
                          name VARCHAR(100) UNIQUE NOT NULL ,
                          price INTEGER NOT NULL ,
                          description VARCHAR(255) NOT NULL ,
                          quantity INTEGER
);