CREATE SCHEMA IF NOT EXISTS order_service;
CREATE TABLE order_service.orders(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL REFERENCES auth.users(id),
    item_id BIGINT NOT NULL REFERENCES catalogue.item_info(id)
);
