env: local
storage_path: no-storage
migration_path: no-migration
port: 8088
smtp:
  host: smtp.office365.com
  port: 587
  sender: 221212@astanait.edu.kz
  username: 221212@astanait.edu.kz
  password: Qqwerty1!
